### ISSUE TITLE
Release for Indigo and Jade

### ISSUE THREAD

**Issue by kmhallen** [dillenberger/pepperl_fuchs#1]
Are there any plans to release this driver to the buildfarm? I can help with this process if desired.

http://wiki.ros.org/bloom/Tutorials

**Comment by dillenberger** [comment]
I don't have any plans, but this might be a good idea.

**Comment by kmhallen** [comment]
I am willing to help. I would need write access to this repository, and write access to an empty pepperl_fuchs-release repository.

**Comment by doisyg** [comment]
What about a release for kinetic, would that be possible?

**Comment by kmhallen** [comment]
Also releasing into kinetic would not be any more difficult.

**Comment by doisyg** [comment]
Great, are there any plans yet to push a release?

**Comment by kmhallen** [comment]
@dillenberger
I am willing to do all the work. I would need write access to this repository, and write access to an empty pepperl_fuchs-release repository.

**Comment by dillenberger** [comment]
@kmhallen 
I just invited you as a collaborator.

**Comment by kmhallen** [comment]
Thanks. I'll get started.

**Comment by kmhallen** [comment]
Released for indigo, jade, and kinetic. It should propagate through the builldfarm in a few days, and be part of the next sync.

Also, I added another launch/rviz example that doesn't depend on `dummy_slam_broadcaster`. We might want to document that on the README and wiki.

**Comment by dillenberger** [comment]
I totally agree.
I actually wanted to get rid of that whole package for months ^^
The time I created this package I wasn't aware of the "fixed frame" parameter in RViz.
So feel free to delete it, otherwise I would definitely do it. :-D
I think, there is no use for it anymore.

Thank you very much for preparing the package for release!

**Comment by kmhallen** [comment]
No problem.

I'll let you decide to remove the extra package or not. It won't affect any of the release work I did.

Also, this issue can probably be closed.
