### ISSUE TITLE
How to set IP laser

### ISSUE THREAD

**Issue by vschiaveto** [dillenberger/pepperl_fuchs#4]
When I run:
rosrun pepperl_fuchs_r2000 r2000_node
I get
IP of laser range finder not set!

Or rosrun pepperl_fuchs_r2000 driver_example

Connecting to scanner at 192.168.1.71 ... Exception: Connection refused
ERROR: Exception: <unspecified file>(1): expected object or array
ERROR: Could not connect to laser range finder!
FAILED!
Connection to scanner at 192.168.1.71 failed!

I couldn't find where I change this IP !

Any help?

**Comment by kmhallen** [comment]
The IP of the scanner can be changed with the two buttons on the physical scanner.

The IP for this ROS driver can be changed with the ```scanner_ip``` parameter. See the link below for an example.  
https://bitbucket.org/DataspeedInc/mobility_base_ros/src/5aa7170bbc262ff5f593c5e1f10b6cf4032190b6/mobility_base_bringup/launch/laser_birdcage_r2000.launch

Also: ```rosrun pepperl_fuchs_r2000 r2000_node scanner_ip:=192.168.1.71```
